### ISSUE TITLE
Error when using template

### ISSUE THREAD

**Issue by lisamariet** [reduxjs/redux-templates#130]
I am using template as specified in docs: 

```
npx create-react-app my-app --template redux

```

but this results in an error:

````
Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template-redux...

(node:93627) ExperimentalWarning: CommonJS module /usr/local/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /usr/local/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

added 1321 packages in 25s

265 packages are looking for funding
  run `npm fund` for details

Initialized a git repository.

Installing template dependencies using npm...
(node:93771) ExperimentalWarning: CommonJS module /usr/local/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /usr/local/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: my-app@0.1.0
npm error Found: react@19.0.0
npm error node_modules/react
npm error   react@"^19.0.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^18.0.0" from @testing-library/react@13.4.0
npm error node_modules/@testing-library/react
npm error   @testing-library/react@"^13.0.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/lisamariet/.npm/_logs/2024-12-12T09_47_50_112Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/lisamariet/.npm/_logs/2024-12-12T09_47_50_112Z-debug-0.log
`npm install --no-audit --save @reduxjs/toolkit@^1.8.1 @testing-library/jest-dom@^5.16.4 @testing-library/react@^13.0.1 @testing-library/user-event@^14.1.1 react-redux@^8.0.1 web-vitals@^2.1.0` failed
````

Seems like the template is not installing the latest [@testing-library/react](https://www.npmjs.com/package/@testing-library/react)

**Comment by markerikson** [comment]
Hmm. We specifically don't recommend using the CRA template any more - CRA is very outdated and not maintained.

Could you try using the Vite template instead?

**Comment by lisamariet** [comment]
Thanks for the input. This is very interesting. I was taking a Codecademy advanced course on react and redux and it recommends using CRA templates. So I guess that is outdated then. I will be sure to let them know as well. 
The course did not include typescript and I see the vite template has typescript. 

It would however be great if you guys could update the readme to say not to use those templates. or if it is possible, also add into the templates themselves when searching for templates that they are outdated?

Again, thanks for your comment. Much appreciated.

**Comment by markerikson** [comment]
Yeah, we'll try to update the READMEs for the CRA templates when we get a chance.

FWIW we did recently update our main docs tutorial to teach Redux using TypeScript as well:

- https://redux.js.org/tutorials/essentials/part-1-overview-concepts

It was a tough decision, because I know TS is one more layer of complexity for beginners to have to learn.  But, we really do want Redux users to use TypeScript - ultimately it ends up saving a lot of time and catching many common mistakes.  So, definitely worth trying to pick up the basics!
