### ISSUE TITLE
Include tests for Counter as example?

### ISSUE THREAD

**Issue by mii9000** [reduxjs/redux-templates#21]

**Comment by nickmccurdy** [comment]
This is a good idea, but let's start it on `cra-template-redux` and then port it here with types: https://github.com/reduxjs/cra-template-redux/issues/23

**Comment by markerikson** [comment]
Fixed by #32, mostly, and I'll do some more tweaks.

**Comment by markerikson** [comment]
I take that back. #32 was just the slice. We could still use some tests for the `Counter` component, but I don't feel like writing them atm.

**Comment by markerikson** [comment]
Superseded by #90 .
